// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPV9IMGecUQPGe4iOzvGMTrSrJUDacU8U',
    appId: '1:341093208219:web:f75cb69cf0a6bffc63f63e',
    messagingSenderId: '341093208219',
    projectId: 'kaapav-app',
    authDomain: 'kaapav-app.firebaseapp.com',
    storageBucket: 'kaapav-app.firebasestorage.app',
    measurementId: 'G-7F5LJLQG0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcA4EDZLWCt4Vi-PnRNqB8xFAgjfRLkdk',
    appId: '1:341093208219:android:d609978e4c5e20d463f63e',
    messagingSenderId: '341093208219',
    projectId: 'kaapav-app',
    storageBucket: 'kaapav-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNJ8c2H3kdpdmvWfZCXj4zkxKypNXyYU',
    appId: '1:341093208219:ios:69b12cccd3a6211863f63e',
    messagingSenderId: '341093208219',
    projectId: 'kaapav-app',
    storageBucket: 'kaapav-app.firebasestorage.app',
    iosBundleId: 'com.example.kaapavApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUNJ8c2H3kdpdmvWfZCXj4zkxKypNXyYU',
    appId: '1:341093208219:ios:69b12cccd3a6211863f63e',
    messagingSenderId: '341093208219',
    projectId: 'kaapav-app',
    storageBucket: 'kaapav-app.firebasestorage.app',
    iosBundleId: 'com.example.kaapavApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPV9IMGecUQPGe4iOzvGMTrSrJUDacU8U',
    appId: '1:341093208219:web:a6769377712fc01263f63e',
    messagingSenderId: '341093208219',
    projectId: 'kaapav-app',
    authDomain: 'kaapav-app.firebaseapp.com',
    storageBucket: 'kaapav-app.firebasestorage.app',
    measurementId: 'G-WQ13K5HVR6',
  );
}
