create extension if not exists pgcrypto;

create table if not exists public.orders (
  order_id text primary key,
  phone text,
  customer_name text,
  items text,
  item_count integer default 0,
  subtotal numeric default 0,
  discount numeric default 0,
  discount_code text,
  shipping_cost numeric default 0,
  tax numeric default 0,
  total numeric default 0,
  shipping_name text,
  shipping_phone text,
  shipping_address text,
  shipping_city text,
  shipping_state text,
  shipping_pincode text,
  status text,
  payment_status text,
  payment_method text,
  payment_id text,
  payment_link text,
  payment_link_expires text,
  paid_at text,
  courier text,
  tracking_id text,
  tracking_url text,
  shipment_id text,
  awb_number text,
  shiprocket_order_id text,
  awb_code text,
  confirmed_at text,
  shipped_at text,
  delivered_at text,
  cancelled_at text,
  customer_notes text,
  internal_notes text,
  cancellation_reason text,
  source text,
  confirmation_sent integer default 0,
  shipping_sent integer default 0,
  delivery_sent integer default 0,
  review_sent integer default 0,
  return_requested integer default 0,
  return_reason text,
  return_requested_at text,
  created_at text,
  updated_at text,
  category text,
  items_summary text
);

create table if not exists public.customers (
  phone text primary key,
  name text,
  email text,
  address text,
  city text,
  state text,
  pincode text,
  segment text,
  tier text,
  labels text,
  message_count integer default 0,
  order_count integer default 0,
  total_spent numeric default 0,
  cart text,
  cart_updated_at text,
  language text,
  opted_in integer default 1,
  first_seen text,
  last_seen text,
  last_order_at text,
  push_subscription text,
  created_at text,
  updated_at text,
  source text,
  labels_summary text,
  cart_item_count integer default 0,
  cart_value numeric default 0,
  unpaid_order_count integer default 0,
  unpaid_order_value numeric default 0
);

create table if not exists public.products (
  sku text primary key,
  name text,
  description text,
  price numeric default 0,
  compare_price numeric default 0,
  cost_price numeric default 0,
  category text,
  subcategory text,
  tags text,
  stock integer default 0,
  reserved_stock integer default 0,
  track_inventory integer default 1,
  image_url text,
  images text,
  video_url text,
  has_variants integer default 0,
  variants text,
  wa_product_id text,
  view_count integer default 0,
  order_count integer default 0,
  is_active integer default 1,
  is_featured integer default 0,
  website_link text,
  material text,
  created_at text,
  updated_at text,
  tags_summary text,
  image_1 text,
  image_2 text,
  image_3 text
);

create table if not exists public.carts (
  phone text primary key,
  items text,
  item_count integer default 0,
  total numeric default 0,
  status text,
  reminder_count integer default 0,
  last_reminder_at text,
  created_at text,
  updated_at text,
  converted_at text,
  customer_name text,
  items_summary text
);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id text not null,
  event_type text not null,
  event_source text,
  message text,
  meta_json text,
  created_at text not null
);

create unique index if not exists order_events_unique_idx
on public.order_events(order_id, event_type, created_at);

create table if not exists public.leads (
  phone text primary key,
  created_at text,
  name text,
  source text,
  category text,
  lead_status text,
  message_count integer default 0,
  order_count integer default 0,
  total_spent numeric default 0,
  segment text,
  tier text,
  labels text,
  labels_summary text,
  last_seen text,
  first_order_at text,
  owner_note text,
  follow_up_needed text,
  updated_at text
);

create table if not exists public.sales (
  order_id text primary key,
  created_at text,
  updated_at text,
  source text,
  category text,
  customer_name text,
  phone text,
  total numeric default 0,
  payment_status text,
  status text,
  paid_at text,
  shipped_at text,
  delivered_at text,
  item_count integer default 0,
  items_summary text,
  sales_stage text,
  owner_note text
);

create table if not exists public.inventory (
  sku text primary key,
  name text,
  category text,
  subcategory text,
  price numeric default 0,
  compare_price numeric default 0,
  stock integer default 0,
  reserved_stock integer default 0,
  status text,
  is_featured text,
  image_url text,
  website_link text,
  material text,
  tags_summary text,
  updated_at text,
  image_1 text,
  image_2 text,
  image_3 text,
  restock_note text
);

create table if not exists public.shipments (
  order_id text primary key,
  customer_name text,
  phone text,
  status text,
  payment_status text,
  shiprocket_order_id text,
  shipment_id text,
  courier text,
  awb_number text,
  awb_code text,
  tracking_id text,
  tracking_url text,
  shipping_city text,
  shipping_state text,
  shipping_pincode text,
  paid_at text,
  shipped_at text,
  delivered_at text,
  updated_at text,
  dispatch_note text,
  dispatch_verified text
);

create table if not exists public.cart_activity (
  phone text primary key,
  customer_name text,
  item_count integer default 0,
  total numeric default 0,
  items_summary text,
  status text,
  reminder_count integer default 0,
  last_reminder_at text,
  created_at text,
  updated_at text,
  converted_at text,
  owner_note text,
  follow_up_needed text
);

create index if not exists idx_orders_phone on public.orders(phone);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_payment_status on public.orders(payment_status);
create index if not exists idx_customers_last_seen on public.customers(last_seen);
create index if not exists idx_products_category on public.products(category);
create index if not exists idx_shipments_status on public.shipments(status);

alter table public.orders disable row level security;
alter table public.customers disable row level security;
alter table public.products disable row level security;
alter table public.inventory disable row level security;
alter table public.carts disable row level security;
alter table public.order_events disable row level security;
alter table public.leads disable row level security;
alter table public.sales disable row level security;
alter table public.shipments disable row level security;
alter table public.cart_activity disable row level security;

grant usage on schema public to service_role, anon, authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;

select
  (select count(*) from public.orders) as orders,
  (select count(*) from public.customers) as customers,
  (select count(*) from public.products) as products,
  (select count(*) from public.carts) as carts,
  (select count(*) from public.order_events) as order_events,
  (select count(*) from public.leads) as leads,
  (select count(*) from public.sales) as sales,
  (select count(*) from public.inventory) as inventory,
  (select count(*) from public.shipments) as shipments,
  (select count(*) from public.cart_activity) as cart_activity;